name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ftp-sync-linux
          - os: windows-latest
            artifact_name: ftp-sync-windows.exe
          - os: macos-latest
            artifact_name: ftp-sync-macos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller colorama

    - name: Build executable
      run: |
        pyinstaller --onefile --name ${{ matrix.artifact_name }} ftp_sync.py

    - name: Upload to Release
      if: github.event.release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.artifact_name }}
